server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    stream:
      function:
        #definition: usersKeySelection;printUsers;productsKeySelection;printProducts;pullProductWatchedByUserEvents;printProductWatchedByUserEvents;countUsersByProductCategory;printCountUsersByProductCategory
        definition: usersKeySelection;printUsers;productsKeySelection;printProducts;pullProductWatchedByUserEvents;countUsersByProductCategory;printCountUsersByProductCategory
        bindings:
          pullProductWatchedByUserEvents-out-0: product-watched-by-user-source
      poller:
        fixed-delay: 2000

      # stream bridge
      source: pullUsers;pullProducts

      kafka:
        streams:
          bindings:
            usersKeySelection-out-0:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.springframework.kafka.support.serializer.JsonSerde
            productsKeySelection-out-0:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$LongSerde
                valueSerde: org.springframework.kafka.support.serializer.JsonSerde
            countUsersByProductCategory-out-0:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$LongSerde


      bindings:
        pullUsers-out-0:
          label: pullUsers-out-0
          destination: users-source
        usersKeySelection-in-0:
          destination: users-source
          group: usersKeySelection-group
        usersKeySelection-out-0:
          destination: users
        printUsers-in-0:
          destination: users
          group: printUsers-group

        pullProducts-out-0:
          label: pullProducts-out-0
          destination: products-source
        productsKeySelection-in-0:
          destination: products-source
          group: productsKeySelection-group
        productsKeySelection-out-0:
          destination: products

        printProducts-in-0:
          destination: products
          group: printProducts-group

        pullProductWatchedByUserEvents-out-0:
          destination: product-watched-by-user-source

        printProductWatchedByUserEvents-in-0:
          destination: product-watched-by-user-source
          group: printProductWatchedByUserEvents-group

        countUsersByProductCategory-in-0:
          destination: product-watched-by-user-source
          group: countUsersByProductCategory-0-group
        countUsersByProductCategory-in-1:
          destination: products
          group: countUsersByProductCategory-1-group
        countUsersByProductCategory-out-0:
          destination: count-users-by-product-category

        printCountUsersByProductCategory-in-0:
          destination: count-users-by-product-category
          group: printCountUsersByProductCategory-group
