package pl.ims.spring.cloud.stream.kafka;

/*
 * Created on 2020-12-18 15:31
 */
public enum Category {
    SMARTPHONE, SMARTWATCH,
    LAPTOP, MACBOOK, PRINTER, MONITOR, SOFTWARE, HEADPHONES, INTELLIGENT_HOUSE, OFFICE, NETWORK, EBOOK_READER,
    TV, AV, HIFI_AUDIO, CAR_AUDIO,
    COFFEE_MACHINE, AIR_PURIFIER,
    WASHING_MACHINE, FRIDGE, MICROWAVE_OVEN,
    DRONE, DIGITAL_CAMERA, CAMERA,

}
